# Generated by Django 3.0.7 on 2020-07-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
